#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)

INSTBOOT_DIR=$RELEASE_DIR/3rdparty/instboot
mkdir -p $INSTBOOT_DIR
cp -a $INSTALL/instboot/* $INSTBOOT_DIR

mkdir -p $INSTBOOT_DIR/dtb
LINUX_DTS_DIR=$(get_build_dir linux)/arch/$TARGET_KERNEL_ARCH/boot/dts
  for dtb in $LINUX_DTS_DIR/amlogic/*.dtb ; do
      cp -a $dtb $INSTBOOT_DIR/dtb
  done
