#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)

if [ -f  .git/config ]; then
  DIR="/home/chewitt/build/LibreELEC.chewitt"
else
  echo "not in git root folder, exiting.."
  exit 1
fi

do_narmstrong(){
  # DRM + AUDIO PATCHES
  rm projects/Amlogic/patches/linux/a-* 2&>/dev/null
  cd ~/linux.narmstrong
  rm *.patch 2&>/dev/null
  git fetch origin linux-4.20-le-amlogic-gx
  git checkout linux-4.20-le-amlogic-gx
  git reset --hard origin/linux-4.20-le-amlogic-gx
  git format-patch --start-number 0001 8fe28cb58bcb235034b64cbbb7550a8a43fd88be # 4.20.0
  for filename in *.patch; do mv "$filename" "a-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
}

#do_upstream(){
  # LINUX PATCHES
#  rm projects/Amlogic/patches/linux/b-* 2&>/dev/null
#  cd ~/linux.narmstrong
#  rm *.patch 2&>/dev/null
#  git checkout linux-4.19-le-amlogic-gx
#  git fetch origin linux-4.19-le-amlogic-gx
#  git reset --hard origin/linux-4.19-le-amlogic-gx
#  git format-patch --start-number 0001 6bf4ca7fbc85d80446ac01c0d1d77db4d91a6d84 #4.19-rc5
  #rm 0001*
  #rm 0003*
#  for filename in *.patch; do mv "$filename" "b-$filename"; done;
#  mv *.patch $DIR/projects/Amlogic/patches/linux/
#}

do_elyotna(){
  # VDEC PATCHES
  rm projects/Amlogic/patches/linux/b-* 2&>/dev/null
  cd ~/linux.elyotna
  rm *.patch 2&>/dev/null
  git checkout 4.20/v4l2-m2m-vp9
  git fetch origin 4.20/v4l2-m2m-vp9
  git reset --hard origin/4.20/v4l2-m2m-vp9
  git format-patch --start-number 0001 8fe28cb58bcb235034b64cbbb7550a8a43fd88be # 4.20.0
  for filename in *.patch; do mv "$filename" "b-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
  cd $DIR
  git checkout projects/Amlogic/patches/linux/b-0005-arm64-dts-meson-add-vdec-entries.patch
}

do_kwiboo(){
  # HDMI AUDIO PATCHES
  rm projects/Amlogic/patches/linux/c-* 2&>/dev/null
  cd ~/linux.kwiboo
  rm *.patch 2&>/dev/null
  git checkout allwinner-4.20-audio
  git fetch origin allwinner-4.20-audio
  git reset --hard origin/allwinner-4.20-audio
  git format-patch --start-number 0001 8fe28cb58bcb235034b64cbbb7550a8a43fd88be # 4.20.0
  for filename in *.patch; do mv "$filename" "c-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
}

do_erstrom(){
  # ath10k-sdio PATCHES
  rm projects/Amlogic/patches/linux/d-* 2&>/dev/null
  cd ~/linux.erstrom
  rm *.patch 2&>/dev/null
  git checkout master
  git fetch origin master
  git reset --hard origin/master
  git format-patch --start-number 0001 94f742967c57a997ab239846be5eb48f5b1458e3 #4.19.0
  for filename in *.patch; do mv "$filename" "d-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
}

do_lima(){
  # LIMA DRIVER
  rm projects/Amlogic/patches/linux/e-* 2&>/dev/null
  cd ~/linux.lima
  rm *.patch 2&>/dev/null
  git fetch origin lima-4.20
  git checkout lima-4.20
  git reset --hard origin/lima-4.20
  git format-patch --start-number 0001 8fe28cb58bcb235034b64cbbb7550a8a43fd88be #4.20.0
  for filename in *.patch; do mv "$filename" "e-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/

  cd $DIR

  # LIMA MESA PATCHES
  rm packages/graphics/mesa/a-* 2&>/dev/null
  cd ~/mesa.lima
  rm *.patch 2&>/dev/null
  git fetch origin lima-18.3
  git checkout lima-18.3
  git reset --hard origin/lima-18.3
  git format-patch --start-number 0001 d81beab96afb403915805435fd4b810a00291b99 #18.3.0
  for filename in *.patch; do mv "$filename" "a-$filename"; done;
  mv *.patch $DIR/packages/graphics/mesa/patches/
}

do_panfrost(){
  # PANFROST MESA PATCHES
  rm packages/graphics/mesa/c-* 2&>/dev/null
  cd ~/mesa.narmstrong
  rm *.patch 2&>/dev/null
  git fetch origin lima-panfrost-18.3
  git checkout lima-panfrost-18.3
  git reset --hard origin/lima-panfrost-18.3
  git format-patch --start-number 0001 d81beab96afb403915805435fd4b810a00291b99 #18.3.0
  for filename in *.patch; do mv "$filename" "c-$filename"; done;
  mv *.patch $DIR/packages/graphics/mesa/patches/
}

case $1 in
  narmstrong)
    do_narmstrong
    ;;
  upstream)
    do_upstream
    ;;
  elyotna|ely)
    do_elyotna
    ;;
  kwiboo)
    do_kwiboo
    ;;
  erstrom|ath10k)
    do_erstrom
    ;;
  lima)
    do_lima
    ;;
  panfrost)
    do_panfrost
    ;;
  all|*)
    do_narmstrong
    do_upstream
    do_elyotna
    do_kwiboo
    do_erstrom
esac

cd $DIR

exit
