#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)

if [ -f  .git/config ]; then
  DIR=$(pwd)
else
  echo "not in git root folder, exiting.."
  exit 1
fi

do_narmstrong(){
  # DRM + AUDIO PATCHES
  rm projects/Amlogic/patches/linux/a-* 2&>/dev/null
  cd ~/linux.narmstrong
  rm *.patch 2&>/dev/null
  git checkout linux-5.0-le-amlogic-gx
  git fetch origin linux-5.0-le-amlogic-gx
  git reset --hard origin/linux-5.0-le-amlogic-gx
  git format-patch --start-number 0001 a3b22b9f11d9fbc48b0291ea92259a5a810e9438 # 5.0-rc7
  for filename in *.patch; do mv "$filename" "a-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
}

do_elyotna(){
  # V4L2 VDEC PATCHES
  rm projects/Amlogic/patches/linux/b-* 2&>/dev/null
  cd ~/linux.elyotna
  rm *.patch 2&>/dev/null
  git checkout 5.0/v4l2-m2m-pr
  git fetch origin 5.0/v4l2-m2m-pr
  git reset --hard origin/5.0/v4l2-m2m-pr
  git format-patch --start-number 0001 8834f5600cf3c8db365e18a3d5cac2c2780c81e5 # 5.0-rc5
  for filename in *.patch; do mv "$filename" "b-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
#  cd $DIR
#  git checkout projects/Amlogic/patches/linux/b-0005-arm64-dts-meson-add-vdec-entries.patch
}

do_kwiboo(){
  # DW-HDMI AUDIO PATCHES
  rm projects/Amlogic/patches/linux/c-* 2&>/dev/null
  cd ~/linux.kwiboo
  rm *.patch 2&>/dev/null
  git fetch origin allwinner-4.20-audio
  git checkout allwinner-4.20-audio
  git reset --hard origin/allwinner-4.20-audio
  git format-patch --start-number 0001 8fe28cb58bcb235034b64cbbb7550a8a43fd88be # 4.20.0
  for filename in *.patch; do mv "$filename" "c-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
}

do_erstrom(){
  # ATH10K-SDIO PATCHES
  rm projects/Amlogic/patches/linux/d-* 2&>/dev/null
  cd ~/linux.erstrom
  rm *.patch 2&>/dev/null
  git fetch origin master
  git checkout master
  git reset --hard origin/master
  git format-patch --start-number 0001 94f742967c57a997ab239846be5eb48f5b1458e3 #4.19.0
  for filename in *.patch; do mv "$filename" "d-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
}

do_lima(){
  # LIMA KERNEL DRIVER
  rm projects/Amlogic/patches/linux/e-* 2&>/dev/null
  cd ~/linux.lima
  rm *.patch 2&>/dev/null
  git fetch origin lima-5.0-rc8-2
  git checkout lima-5.0-rc8-2
  git reset --hard origin/lima-5.0-rc8-2
  git format-patch --start-number 0001 5908e6b738e3357af42c10e1183753c70a0117a9 #5.0.0-rc8
  for filename in *.patch; do mv "$filename" "e-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
}

do_panfrost(){
  # PANFROST KERNEL DRIVER
  rm projects/Amlogic/patches/linux/f-* 2&>/dev/null
  cd ~/linux.panfrost
  rm *.patch 2&>/dev/null
  git fetch origin panfrost-5.0
  git checkout panfrost-5.0
  git reset --hard origin/panfrost-5.0
  git format-patch --start-number 0001 12ad143e1b803e541e48b8ba40f550250259ecdd #5.0.0
  for filename in *.patch; do mv "$filename" "f-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
  cd $DIR
  rm projects/Amlogic/patches/linux/f-0009-drm-Add-reservation_object-to-drm_gem_object.patch
  rm projects/Amlogic/patches/linux/f-0017-drm-doc-document-recommended-component-helper-usage.patch
}

do_nondrm(){
  # PANFROST NONDRM MESA PATCHES
  rm packages/graphics/mesa/patches/panfrost/a-* 2&>/dev/null
  cd ~/panfrost.nondrm
  rm *.patch 2&>/dev/null
  git fetch origin master
  git checkout master
  git reset --hard origin/master
  git format-patch --start-number 0001 a98efe3901c3b4d6cc7587b0909d6fb9c49e8323 #nondrm
  for filename in *.patch; do mv "$filename" "a-$filename"; done;
  sed -i 's|a/|a/src/gallium/drivers/panfrost/nondrm/|g' *.patch
  sed -i 's|b/|b/src/gallium/drivers/panfrost/nondrm/|g' *.patch
  mv *.patch $DIR/packages/graphics/mesa/patches/panfrost/
}

case $1 in
  narmstrong)
    do_narmstrong
    ;;
  upstream)
    do_upstream
    ;;
  elyotna|ely)
    do_elyotna
    ;;
  kwiboo)
    do_kwiboo
    ;;
  erstrom|ath10k)
    do_erstrom
    ;;
  lima)
    do_lima
    ;;
  panfrost)
    do_panfrost
    ;;
  nondrm)
    do_nondrm
    ;;
  *)
    echo "error: nothing selected!"
    ;;
esac

cd $DIR

exit
